# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b944ed5df91eaa4d221b4b89df05a19d9bba7f57dcd09ff9e07ec4bd2544c1131440f7c9099b9df6c6cb21c81e1121001996278defb605171a75ea7242ae748

test:
  secret_key_base: 6255d0494b218950d2e01c0fa41c9b11059bcc7285ccdbb765907f470a968b97101c7cadd9f390854a661ac278775d1065f125bc7571444481a3d749e8a24e64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
